# MaaSAuthPolicy granting access to the simulator model for users in the listed groups.
# The controller will create one Kuadrant AuthPolicy per model targeting that model's HTTPRoute.
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: simulator-access
  namespace: opendatahub
spec:
  modelRefs:
    - facebook-opt-125m-simulated
  subjects:
    groups:
      - name: free-user
    users: []
